apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ .Values.global.serviceAccount.name }}-workload-identity
  namespace: {{ .Release.Namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.projectID }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cnrm-{{ .Values.global.serviceAccount.name }}
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.global.projectID }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.global.serviceAccount.name }}]
