apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cnrm-{{ .Values.global.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.projectID }}
spec:
  displayName: CNRM ServiceAccount for {{ .Values.global.serviceAccount.name }}
