{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: cnrm-{{ .Values.global.serviceAccount.name }}@{{ .Values.global.projectID }}.iam.gserviceaccount.com
{{- end }}
